### ISSUE TITLE
Test with hotspot jdk12 error message

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-microprofile-rest-client-async#19]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running it.io.openliberty.guides.system.SystemEndpointTest
Exception in thread "tcp-unix-proxy-accept-thread" java.lang.ExceptionInInitializerError
	at org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:36)
	at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:54)
	at org.rnorth.tcpunixsocketproxy.TcpToUnixSocketProxy.lambda$start$0(TcpToUnixSocketProxy.java:86)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:42)
	... 4 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:35)
	... 4 more
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/jz/f6znzpf11qz__b_55ws5kh_h0000gn/T/libjunixsocket-native-2.0.44745334894089160322.dylib: dlopen(/private/var/folders/jz/f6znzpf11qz__b_55ws5kh_h0000gn/T/libjunixsocket-native-2.0.44745334894089160322.dylib, 1): no suitable image found.  Did find:
	/private/var/folders/jz/f6znzpf11qz__b_55ws5kh_h0000gn/T/libjunixsocket-native-2.0.44745334894089160322.dylib: code signature in (/private/var/folders/jz/f6znzpf11qz__b_55ws5kh_h0000gn/T/libjunixsocket-native-2.0.44745334894089160322.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:765)
	at java.base/java.lang.System.load(System.java:1866)
	at org.newsclub.net.unix.NarSystem.loadLibrary(NarSystem.java:39)
	... 9 more
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 11.29 s <<< FAILURE! - in it.io.openliberty.guides.system.SystemEndpointTest
[ERROR] testGetProperties(it.io.openliberty.guides.system.SystemEndpointTest)  Time elapsed: 0.012 s  <<< ERROR!
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at it.io.openliberty.guides.system.SystemEndpointTest.<init>(SystemEndpointTest.java:68)

[ERROR] testRunJob(it.io.openliberty.guides.system.SystemEndpointTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
	at it.io.openliberty.guides.system.SystemEndpointTest.<init>(SystemEndpointTest.java:68)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   SystemEndpointTest.<init>:68 » IllegalState Could not find a valid Docker envi...
[ERROR]   SystemEndpointTest.<init>:68 » IllegalState Previous attempts to find a Docker...
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0

Java version info: 

openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode)

**Comment by evelinec** [comment]
Discussed with team, JDK12 is not a supported level yet. Closed.
