### ISSUE TITLE
Peer review feedback

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-microprofile-rest-client-async#9]
What you'll learn

- [ ] IMO, in the first paragraph, where the `CompletionStage` class is first mentioned, it may be good to call it out as "a completion stage class".. or otherwise, add link to where more info can be found for the class. 
=> Gilbert suggested to use `CompletionStage` interface

- [x] May be good to spell out the first occurrence of "IO". 

- [ ] "Going back to the restaurant analogy, food is prepared asynchronously in the kitchen and your waiter is freed up to attend to other tables. " => Not sure food is really prepared asynchronously.. either "the food orders are taken asynchronously and your waiter can to attend to other tables.." or "while food is prepared in the kitchen, your waiter can attend to other tables." 

- [ ] Since they’re free, the waiter can take more orders from other tables, or serve food to other tables. => Perhaps "As a result, the waiter can take more orders.." 

- [ ] These lengthy operations can block the execution of your thread when it’s in use and prevent other work from being completed. => it feels like one more statement can follow after this one. Perhaps "After updating to asynchronous REST client calls, the threads can continue to do work while some are waiting."? (TBD)

- [x] The application you will be working with is a job runner that mantains an inventory of available systems.  
=> Change "job runner" to "job manager" perhaps? Just "job runner" sounds odd to me. 
=> "mantains" typo

- [x] When it completes, the system microservice publishes the sleep time as the result of this job. => Change "publishes" to "reports"? or "prints"? 

- [x] Finally, the gateway microservice is a backend for front end. It communicates with the backend job and inventory microservices on the caller’s behalf. => From the link, the BFF is spelled as " backend for frontend", good to keep it consistent that way. 

- [ ] Not fond of the `gateway` being the service name.. Maybe "ServiceGateway" to be more specific? 

- [x] The picture isn't showing up

- [x] In the picture, I think can rename "Job Manager" to "Job" to match with the service name. I think "Manager" is just part of the actions for the `Job` service. 

- [x] If you are not too familiar with MicroProfile Rest Client, then read the Consuming RESTful services with template interfaces guide to learn more about it.
=> change to "If you not are familiar with MicroProfile Rest Client" or "If you want to learn more about MicroProfile Rest Client, you can read the Consuming RESTful services with template interfaces guide." 
=> no need to mention "then"

Changing the template interface to use asynchronous methods

- [x] First, you will replace the job client interface to make the methods asynchronous. => First, you will make the job client interface methods asynchronous. (I think this is clearer.)

Responding asynchronously to an HTTP request

- [ ] AX-RS resources can also have asynchronous methods. So instead of returning a JobsListModel type, you may return a CompletionStage<JobsListModel> type. => the return types, `JobsListModel` and `CompletionStage<JobsListModel> ` can have hotspots, where appropriate.

- [ ] Finally, return the CompletionStage<JobsListModel> you built up using the thenApplyAsync(). => would be helpful to add hotspot for the mentioned class name and method here too. 

- [ ] When you return a CompletionStage in the resource, it doesn’t necessarily mean that the computation has completed and the response has been built. JAX-RS will respond to the caller once the CompletionStage has completed. => I think this two sentences means, "When you return a CompletionStage in the resource, it doesn’t necessarily mean that the computation has completed and the response has been built. JAX-RS will build a respond to the caller once the all of the stages for this CompletionStage have completed." TBD

Building and running the application

- [x] Running the `mvn clean package` command requires Docker to be running, but it's not mentioned as a prereq. 

- [x] After started the app, accessing the job endpoints, may be good to give examples of the POST action to create a job. ie, on Mac, `curl -X POST http://localhost:8080/api/jobs`

- [x] On Linux, the `mvn clean package` command failed for the `inventory` service and onwards. The maven version was v3.3.6, after upgrading to v3.5.4, the app is packaged successfully. 

- [x] After starting the app, there's a bit of delay till the endpoints are ready. It displays blank page for a few seconds, right after app start. 

- [x] After a POST action to create a job, it take a few seconds (up to 5 seconds) to get updated in the jobs list too. 

- [x] In the jobs list endpoint, what do `averageResult` and `result` mean? 

- [x] On Linux, after started the app, accessing the endpoints give "context root not found" for a while (~5 minutes) before it becomes available. Each POST request made take some time (~5 seconds) to get updated as well. 

- [x] On Windows, it takes 13 minutes to build (ran `mvn clean package` command). 

- [x] It also spawns containers for kafka, zookeeper, and all of the microservices in the project. => The kafka, zookeeper containers are being introduced for the first time and there's no descriptions for them? 

Testing the gateway application

- [x] If a test failure occurs, then you might have introduced a bug into the code. => If a test failure occurs, then you may have introduced a bug in the code.

- [x] On Linux, the tests took quite a while to run, 10 - 20 minutes? 

- [x] On Linux, the `InventoryEndpointTest` failed: 

```
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running it.io.openliberty.guides.inventory.InventoryEndpointTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 24.478 s <<< FAILURE! - in it.io.openliberty.guides.inventory.InventoryEndpointTest
[ERROR] testConsumeSystem(it.io.openliberty.guides.inventory.InventoryEndpointTest)  Time elapsed: 13.267 s  <<< FAILURE!
java.lang.AssertionError: expected:<200> but was:<404>
	at it.io.openliberty.guides.inventory.InventoryEndpointTest.testConsumeSystem(InventoryEndpointTest.java:109)
```

- [x] On Windows, the tests also failed with the similar error message as the Linux one, for the `system` service. 

- [x] The following failure message in the test logs can be handled?

```
Failed to load class "org.slf4j.impl.StaticLoggerBinder".
Defaulting to no-operation (NOP) logger implementation
See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Teardown

- [x] Finally, use the provided script to stop the application. => Finally, use the script to stop the application.

Overall, the application and building the services in the containers are heavy, and it feels like not much was being explained in the guide. 

- [x] A lot of codes, ie, inventory, system, and job services are provided, perhaps good to mentioned that. 

- [ ] Do we need to build all services in the container? Are there values for using containers for this guide? Would running some of the services locally be faster to start up, perhaps? 
=> Gilbert explained that this was by original design. May discuss with YK again.

**Comment by evelinec** [comment]
On Windows, the tests are still failing, here's the error message: 

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running it.io.openliberty.guides.inventory.InventoryEndpointTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
        ?? Checking the system...
        ? Docker version should be at least 1.6.0
        ? Docker environment should have more than 2GB free disk space
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.627 s <<< FAILURE! - in it.io.openliberty.guides.inventory.InventoryEndpointTest
[ERROR] testConsumeSystem(it.io.openliberty.guides.inventory.InventoryEndpointTest)  Time elapsed: 6.055 s  <<< ERROR!
java.io.FileNotFoundException: C:\Users\JUSTINEChen\AppData\Local\Temp\surefire1774764770569861118\..%5C..%5C..%5C..%5C..%5CJUSTINEChen%5Cecguides%5Cdraft-guide-microprofile-rest-client-async%5Cfinish%5Cinventory%5Ctarget%5Ctest-classes\props.json (The system cannot find the path specified)
        at it.io.openliberty.guides.inventory.InventoryEndpointTest.getResource(InventoryEndpointTest.java:174)
        at it.io.openliberty.guides.inventory.InventoryEndpointTest.testConsumeSystem(InventoryEndpointTest.java:115)

[INFO]

**Comment by evelinec** [comment]
On Linux, the tests failure was due to port conflict. After resolving that, all of the tests were ran successfully.

**Comment by evelinec** [comment]
Working with Steven on the image and table scrolling issues.
